#!/bin/bash
# Block writes to sensitive or generated files before they happen.
#
# This hook fires on every PreToolUse event for Edit and Write tools.
# It checks the target file path against a blocklist of patterns and
# denies the operation if the file should not be modified by agents.
#
# Exit codes:
#   0 - File is allowed (not blocked)
#   2 - File is blocked (deny with reason — message surfaced to agent)

set -euo pipefail

# ---------------------------------------------------------------------------
# 1. Read hook input
# ---------------------------------------------------------------------------
INPUT=$(cat)

# Extract the file path from the hook payload.
# Write supplies tool_input.file_path; Edit supplies tool_input.path.
FILE_PATH=$(echo "$INPUT" | jq -r '
  .tool_input.file_path //
  .tool_input.path //
  ""
')

if [ -z "$FILE_PATH" ]; then
  # Cannot determine file — allow by default
  exit 0
fi

# ---------------------------------------------------------------------------
# 2. Check against block patterns
# ---------------------------------------------------------------------------
BASENAME=$(basename "$FILE_PATH")

# Secrets: .env, .env.local, .env.production, etc.
case "$BASENAME" in
  .env|.env.*)
    echo "BLOCKED: $FILE_PATH — .env files contain secrets and must not be modified by agents."
    exit 2
    ;;
esac

# Lock files: these are generated and must not be hand-edited
case "$BASENAME" in
  package-lock.json|pnpm-lock.yaml)
    echo "BLOCKED: $FILE_PATH — lock files are generated by package managers. Run install commands instead."
    exit 2
    ;;
esac

# Git internals: never touch .git/
case "$FILE_PATH" in
  *.git/*|.git/*)
    echo "BLOCKED: $FILE_PATH — .git internals must not be modified directly."
    exit 2
    ;;
esac

# ---------------------------------------------------------------------------
# 3. File is allowed
# ---------------------------------------------------------------------------
exit 0
